dns:
  image: devries/dnsmasq
  links:
  - mesosmaster
  - slave1
  - slave2
  - slave3
mesosmaster:
  image: redjack/mesos-master:0.21.0
  hostname: mesosmaster
  environment:
    - MESOS_QUORUM=1
    - MESOS_WORK_DIR=/var/lib/mesos
    - MESOS_LOG_DIR=/var/log
  volumes:
    - /var/log/mesos:/var/log/mesos
  ports:
    - "5050:5050"
slave1:
  image: redjack/mesos-slave:0.21.0
  hostname: slave1
  links:
   - mesosmaster
  environment:
    - MESOS_MASTER=mesosmaster:5050
    - MESOS_EXECUTOR_REGISTRATION_TIMEOUT=5mins
    - MESOS_CONTAINERIZERS=docker,mesos
    - MESOS_ISOLATOR=cgroups/cpu,cgroups/mem
    - MESOS_LOG_DIR=/var/log
    - MESOS_RESOURCES=ports(*):[31000-31100]
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker:ro
    - /sys:/sys:ro
    - /var/log/mesos:/var/log/mesos
slave2:
  image: redjack/mesos-slave:0.21.0
  hostname: slave2
  links:
   - mesosmaster
  environment:
    - MESOS_MASTER=mesosmaster:5050
    - MESOS_EXECUTOR_REGISTRATION_TIMEOUT=5mins
    - MESOS_CONTAINERIZERS=docker,mesos
    - MESOS_ISOLATOR=cgroups/cpu,cgroups/mem
    - MESOS_LOG_DIR=/var/log
    - MESOS_RESOURCES=ports(*):[31200-31300]
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker:ro
    - /sys:/sys:ro
    - /var/log/mesos:/var/log/mesos
slave3:
  image: redjack/mesos-slave:0.21.0
  hostname: slave3
  links:
   - mesosmaster
  environment:
    - MESOS_MASTER=mesosmaster:5050
    - MESOS_EXECUTOR_REGISTRATION_TIMEOUT=5mins
    - MESOS_CONTAINERIZERS=docker,mesos
    - MESOS_ISOLATOR=cgroups/cpu,cgroups/mem
    - MESOS_LOG_DIR=/var/log
    - MESOS_RESOURCES=ports(*):[31400-31500]
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker:ro
    - /sys:/sys:ro
    - /var/log/mesos:/var/log/mesos
scheduler:
  image: mesos/elasticsearch-scheduler
  command: "-d -m mesosmaster -dns dns -n 3 -nn localhost"
  links:
   - mesosmaster
   - dns

