master:
  image: redjack/mesos-master:0.21.0
  hostname: master
  environment:
    - MESOS_QUORUM=1
    - MESOS_WORK_DIR=/var/lib/mesos
    - MESOS_LOG_DIR=/var/log
  volumes:
    - /var/log/mesos:/var/log/mesos
  ports:
    - "5050:5050"
slave1:
  image: redjack/mesos-slave:0.21.0
  links:
    - master:master
  environment:
    - MESOS_MASTER=master:5050
    - MESOS_EXECUTOR_REGISTRATION_TIMEOUT=5mins
    - MESOS_CONTAINERIZERS=docker,mesos
    - MESOS_ISOLATOR=cgroups/cpu,cgroups/mem
    - MESOS_LOG_DIR=/var/log
    - MESOS_RESOURCES=ports(*):[9200-9200,9300-9300]
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/local/bin/docker:/usr/local/bin/docker:ro
    - /sys:/sys:ro
    - /var/log/mesos:/var/log/mesos
  ports:
    - "5051:5051"
scheduler:
  image: mesos/elasticsearch-scheduler
  command: "-d -m master:5050 -n 1 -nn master"
  links:
   - master:master

